Repository sotocodev/facebook_clone, pull requests merged in 2024-03, with the labels that each got.

#10 Fc 10
  src/UI/Molecules/ImgPublicate/ImgPublicate.jsx
  src/UI/Molecules/ImgPublicate/ImgPublicate.module.css
  src/UI/Molecules/PublicateNicknameBar/PublicateNicknameBar.jsx
  src/UI/Molecules/PublicateNicknameBar/PublicateNicknameBar.module.css
  src/UI/Molecules/PublicateOptionsBar/PublicateOptionsBar.jsx
  src/UI/Molecules/PublicateOptionsBar/PublicateOptionsBar.module.css
  src/UI/Molecules/PublicationBar/PublicationBar.jsx
  src/UI/Molecules/PublicationBar/PublicationBar.module.css
  src/UI/Organims/Publicate/PublicateZone.jsx
  src/UI/Organims/Publicate/PublicateZone.module.css
  src/UI/atoms/ButtonTo/ButtonTo.jsx
  src/UI/atoms/ButtonTo/ButtonTo.module.css
  src/UI/atoms/IconProfile/IconProfile.jsx
  src/UI/atoms/IconProfile/IconProfile.module.css
  src/UI/atoms/Img/Img.jsx
  src/UI/atoms/Input/Input.jsx
  src/UI/atoms/Nickname/Nickname.jsx
  src/UI/atoms/Nickname/Nickname.module.css
  src/UI/atoms/PublicateButton/PublicateButton.jsx
  src/UI/atoms/PublicateButton/PublicateButton.module.css
  src/UI/templates/HomeTemplate/HomeTemplate.jsx
  src/assets/Icons/Camare.png
  src/assets/Icons/Close.svg
  src/assets/Icons/Comment.svg
  src/assets/Icons/Gokupelon.jpeg
  src/assets/Icons/Like.svg
  src/assets/Icons/Points.svg
  src/assets/Icons/Profile.png
  src/assets/Icons/Share.svg
  src/assets/Icons/Smile.png
  src/assets/Icons/photo.png
Labels: No solucionado

#6 Fc 9 slide principal
  public/ArrowToLeft.svg
  public/ArrowToRight.svg
  public/history.jpg
  public/profile.jpg
  src/UI/atoms/Button/Button.jsx
  src/UI/atoms/Button/Button.module.css
  src/UI/atoms/Img/Img.jsx
  src/UI/molecules/Cards/CardHistory/CardHistory.jsx
  src/UI/molecules/Cards/CardHistory/CardHistory.module.css
  src/UI/organins/SlidePrincipal/SlidePrincipal.jsx
  src/UI/organins/SlidePrincipal/SlidePrincipal.module.css
  src/UI/templates/HomeTemplate/HomeTemplate.jsx
  src/assets/img/history.jpg
  src/assets/img/profile.jpg
  src/main.jsx
Labels: No solucionado

#12 ajustes de Historias y Publicaciones
  src/UI/Molecules/CardHistory/CardHistory.jsx
  src/UI/Molecules/CardHistory/CardHistory.module.css
  src/UI/Molecules/ImgPublicate/ImgPublicate.module.css
  src/UI/Molecules/PublicateOptionsBar/PublicateOptionsBar.jsx
  src/UI/Organims/Publicate/PublicateZone.module.css
  src/UI/Organims/SlidePrincipal/SlidePrincipal.jsx
  src/UI/Organims/SlidePrincipal/SlidePrincipal.module.css
  src/UI/atoms/Nickname/Nickname.jsx
  src/UI/templates/HomeTemplate/HomeTemplate.jsx
Labels: vercel error

#15 marketplace
  src/App.jsx
  src/UI/Molecules/ImgPublicate/ImgPublicate.jsx
  src/UI/Molecules/PublicateNicknameBar/PublicateNicknameBar.jsx
  src/UI/Molecules/PublicationBar/PublicationBar.jsx
  src/UI/Organims/Publicate/PublicateZone.jsx
  src/UI/atoms/Icon/Icon.jsx
  src/UI/atoms/Icon/Icon.module.css
  src/UI/atoms/IconProfile/IconProfile.jsx
  src/UI/atoms/IconProfile/IconProfile.module.css
  src/UI/atoms/Input/Input.jsx
  src/UI/atoms/Input/Input.module.css
  src/UI/organisms/Publicate/PublicateZone.jsx
  src/UI/organisms/Publicate/PublicateZone.module.css
  src/UI/organisms/SidebarMarletplaces/SidebarMarletplaces.jsx
  src/UI/organisms/SidebarMarletplaces/SidebarMarletplaces.module.css
  src/UI/organisms/SlidePrincipal/SlidePrincipal.jsx
  src/UI/organisms/SlidePrincipal/SlidePrincipal.module.css
  src/UI/templates/HomeTemplate/HomeTemplate.jsx
  src/UI/templates/MarketplacesTemplate/MarketplacesTemplate.jsx
  src/UI/templates/MarketplacesTemplate/MarketplacesTemplate.module.css
  src/assets/css/Global.css
  src/assets/css/Navbar.css
  src/assets/css/Sidebar.css
  src/assets/img/history.jpg
  src/assets/img/profile.jpg
  src/pages/Marketplaces.jsx
  src/routes/RoutesProvider.jsx
Labels: comentarios

#19 Fc 10 fixed
  public/Camare.png
  public/Close.svg
  public/Comment.svg
  public/Gokupelon.jpeg
  public/ImgTribute.jpg
  public/Like.svg
  public/Points.svg
  public/Profile.png
  public/Share.svg
  public/Smile.png
  public/photo.png
  src/UI/molecules/CardHistory/CardHistory.jsx
  src/UI/molecules/CardHistory/CardHistory.module.css
  src/UI/molecules/ImgPublicate/ImgPublicate.jsx
  src/UI/molecules/ImgPublicate/ImgPublicate.module.css
  src/UI/molecules/PublicateNicknameBar/PublicateNicknameBar.jsx
  src/UI/molecules/PublicateNicknameBar/PublicateNicknameBar.module.css
  src/UI/molecules/PublicateOptionsBar/PublicateOptionsBar.jsx
  src/UI/molecules/PublicateOptionsBar/PublicateOptionsBar.module.css
  src/UI/molecules/PublicationBar/PublicationBar.jsx
  src/UI/molecules/PublicationBar/PublicationBar.module.css
  src/UI/organisms/Publicate/PublicateZone.jsx
  src/UI/organisms/SlidePrincipal/SlidePrincipal.jsx
Labels: aprobado
